baseURL = "http://www.pieralberto."
title = "Pier Alberto Pierini"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"
# paginate = 20
pygmentsStyle = "bw"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji = true

[params]
author = "Pier Alberto Pierini"
description = "Pier Alberto's personal website"
keywords = "resume,IT,personal"
info = ["The IT Samurai Spirit", "Never Give Up spirit"]
avatarURL = "images/avatar.jpg"
#gravatar = "pieralbertopierini@gmail.com"
footerContent = "The IT Samurai"
dateFormat = "January 2, 2006"
hideFooter = false
hideCredits = false
hideCopyright = false
since = 2017
# Right To Left, shift content direction for languages such as Arabic
rtl = false
# Specify light/dark colorscheme
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorScheme = "auto"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false
# Series see also post count
maxSeeAlsoItems = 5
# Enable Twemoji
enableTwemoji = false
# Custom CSS
customCSS = []
# Custom SCSS
customSCSS = []
# Custom JS
customJS = []

# If you want to implement a Content-Security-Policy, add this section
[params.csp]
childsrc = ["'self'"]
fontsrc = ["'self'", "https://fonts.gstatic.com", "https://cdn.jsdelivr.net/"]
formaction = ["'self'"]
framesrc = ["'self'"]
imgsrc = ["'self'"]
objectsrc = ["'none'"]
stylesrc = [
  "'self'",
  "'unsafe-inline'",
  "https://fonts.googleapis.com/",
  "https://cdn.jsdelivr.net/"
]
scriptsrc = ["'self'", "'unsafe-inline'", "https://www.google-analytics.com"]
prefetchsrc = ["'self'"]
# connect-src directive – defines valid targets for to XMLHttpRequest (AJAX), WebSockets or EventSource
connectsrc = ["'self'", "https://www.google-analytics.com"]

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
  name = "Github"
  icon = "fa fa-github"
  weight = 1
  url = "https://github.com/PierAlbertoPierini"

# [[params.social]]
#   name = "Twitter"
#   icon = "fa fa-twitter"
#   weight = 3
#   url = "https://twitter.com/johndoe/"

[[params.social]]
  name = "LinkedIn"
  icon = "fa fa-linkedin"
  weight = 4
  url = "https://www.linkedin.com/in/pieralbertopierini"

[languages]
  [languages.en]
    weight = 10
    languageName = "English"
    languageCode = "en-us"

  [[languages.en.menu.main]]
    name = "About"
    weight = 10
    url = "about/"

  [[languages.en.menu.main]]
    name = "Contact"
    weight = 20
    url = "contact/"

  [[languages.en.menu.main]]
    name = "Education"
    weight = 30
    url = "education/"

  [[languages.en.menu.main]]
    name = "Experiences"
    weight = 40
    url = "experiences/"

  [[languages.en.menu.main]]
    name = "ProDev"
    weight = 50
    url = "professionaldev/"

  [[languages.en.menu.main]]
    name = "Projects"
    weight = 60
    url = "projects/"

  [[languages.en.menu.main]]
    name = "Varia"
    weight = 70
    url = "varia/"

#  [languages.it]
#    weight = 20
#    languageName = "Italiano"
#    languageCode = "it-it"
#
#  [languages.it.params]
#    info = ["IT Samurai", "Spirito Indomito"]
#    description = "Sito personale di Pier Alberto Pierini"
#    keywords = "MSP,IT support,personale"
#    footerContent = ""
#
#  [[languages.it.menu.main]]
#    name = "Chi sono"
#    weight = 1
#    url = "about/"
#
#  [languages.fr]
#   weight = 30
#   languageName = "French"
#   languageCode = "fr-fr"
#
#  [languages.fr.params]
#   info = ""
#   description = ""
#   keywords = ""
#   footerContent = ""
#
#  [[languages.fr.menu.main]]
#   name = "qui nous sommes"
#   weight = 1
#   url = "about/"